datawarehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host_rds
      user: usuario_rds
      pass: pass_rds
      port: 5432
      dbname: datawarehouse
      schema: public
      threads: 4
sandbox:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host_rds
      user: usuario_rds
      pass: pass_rds
      port: 5432
      dbname: sandbox
      schema: public
      threads: 4